INSERT INTO CITY VALUES(SQ_CITY_KEY.NEXTVAL, 'Warsaw');
INSERT INTO CITY VALUES(SQ_CITY_KEY.NEXTVAL, 'Madrid');

INSERT INTO PLACE VALUES(SQ_PLACE_KEY.NEXTVAL, 'Piłkarska 19', (SELECT CITY_KEY FROM CITY WHERE NAME = 'Warsaw'));
INSERT INTO PLACE VALUES(SQ_PLACE_KEY.NEXTVAL, 'Wanda Metropolitano', (SELECT CITY_KEY FROM CITY WHERE NAME = 'Madrid'));